

document.getElementById('encrypt-button').addEventListener('click', async function () {
  // Add styling of longer than 20 strings- for long keys
  addStyleToHeadForTruncatedText();

  // Clear output block
  while (document.getElementById('output').firstChild) {
    document.getElementById('output').removeChild(document.getElementById('output').firstChild);
  }

  // Animation code:
  const dotContainer = document.querySelector('.passing-dots1');
  const dotCount = 6;
  const dotDuration = 2000; // Each dot appears for 0.5 seconds
  const delayBetweenDots = 150;
  for (let i = dotCount; i > 0; i--) {
    setTimeout(() => {
      const dot = document.createElement('div');
      dot.classList.add('dot');
      dotContainer.appendChild(dot);

      setTimeout(() => dot.remove(), dotDuration);
    }, i * delayBetweenDots);
  }

  setTimeout(() => {
    for (let i = dotCount; i > 0; i--) {
      setTimeout(() => {
        const dot = document.createElement('div');
        dot.classList.add('dot');
        dotContainer.appendChild(dot);

        setTimeout(() => dot.remove(), dotDuration);
      }, i * delayBetweenDots);
    }
  }, 2750);

  setTimeout(() => {
    for (let i = dotCount; i > 0; i--) {
      setTimeout(() => {
        const dot = document.createElement('div');
        dot.classList.add('dot');
        dotContainer.appendChild(dot);

        setTimeout(() => dot.remove(), dotDuration);
      }, i * delayBetweenDots);
    }
  }, 5500);


  // Get input values
  const cardNumber = document.getElementById('card-number').value;
  const name = document.getElementById('name').value;
  const passcode = document.getElementById('passcode').value;
  const cvc = document.getElementById('cvc').value;

  console.log(cvc);

  // Perform encryption (you'll need a suitable encryption library)
  // Example using a simple placeholder, not secure!


  // Update output block
  outputElement = document.getElementById('output');
  bankElement = document.getElementById('bank');

  //document.getElementById('passing-dots').style.display = "block";


  // Display message to send
  const sentenceLine = document.createElement('p');
  sentenceLine.style.margin = "3px";
  sentenceLine.style.color = "green";
  sentenceLine.style.textDecoration = "underline";

  const sentenceToSend = await getPublicKeyData("SentenceToSend")
  const sentenceShortened = createTruncatedTextElement(sentenceToSend.Sentence, 35);

  setTimeout(() => outputElement.appendChild(sentenceLine), 500);
  setTimeout(() => sentenceLine.textContent = "Requested message to encrypt:", 500);
  setTimeout(() => outputElement.appendChild(sentenceShortened), 500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // Display the secret keys created by the user
  const publicKeyLine1 = document.createElement('p');
  publicKeyLine1.style.margin = "3px";
  publicKeyLine1.style.color = "green";
  publicKeyLine1.style.textDecoration = "underline";

  const publicKeyLine2 = document.createElement('p');
  publicKeyLine2.style.margin = "3px";
  publicKeyLine2.style.color = "green";
  publicKeyLine2.style.textDecoration = "underline";

  const privateKeyLine1 = document.createElement('p');
  privateKeyLine1.style.margin = "3px";
  privateKeyLine1.style.color = "green";
  privateKeyLine1.style.textDecoration = "underline";

  const privateKeyLine2 = document.createElement('p');
  privateKeyLine2.style.margin = "3px";
  privateKeyLine2.style.color = "green";
  privateKeyLine2.style.textDecoration = "underline";

  const PublicKeys = await getPublicKeyData("PublicKeys");
  const PrivateKeys = await getPublicKeyData("SecretKeys");
  const user_public = createTruncatedTextElement(PublicKeys.user_public_key, 35);
  const bank_public = createTruncatedTextElement(PublicKeys.bank_public_key, 35);
  const user_private = createTruncatedTextElement(PrivateKeys.user_private, 35);
  const bank_private = createTruncatedTextElement(PrivateKeys.bank_private, 35);
  const user_schnorr = createTruncatedTextElement(PrivateKeys.sch_key, 35);

  // User generated public key:
  setTimeout(() => outputElement.appendChild(publicKeyLine1), 3500);
  setTimeout(() => publicKeyLine1.textContent = "User generated public key", 3500);
  setTimeout(() => outputElement.appendChild(user_public), 3500);

  // Bank generated public key:
  setTimeout(() => outputElement.appendChild(publicKeyLine2), 4500);
  setTimeout(() => publicKeyLine2.textContent = "Bank generated public key:", 4500);
  setTimeout(() => outputElement.appendChild(bank_public), 4500);

  // Private user key generated by the user:
  setTimeout(() => outputElement.appendChild(privateKeyLine1), 1500);
  setTimeout(() => privateKeyLine1.textContent = "User generated private key:", 1500);
  setTimeout(() => outputElement.appendChild(user_private), 1500);

  // Private bank key generated by the user:
  setTimeout(() => outputElement.appendChild(privateKeyLine2), 2500);
  setTimeout(() => privateKeyLine2.textContent = "Bank generated private key:", 2500);
  setTimeout(() => outputElement.appendChild(bank_private), 2500);

  const bothGenerate = document.createElement('p');
  bothGenerate.style.margin = "3px";
  bothGenerate.style.color = "green";
  const bothGenerate2 = document.createElement('p');
  bothGenerate2.style.margin = "3px";
  bothGenerate2.style.color = "green";
  bothGenerate2.style.textDecoration = "underline";

  setTimeout(() => outputElement.appendChild(bothGenerate), 5500);
  setTimeout(() => bothGenerate.textContent = "User and bank exchange their public", 5500);
  setTimeout(() => outputElement.appendChild(bothGenerate2), 5500);
  setTimeout(() => bothGenerate2.textContent = "keys to create the shared key :", 5500);

  const sharedKey = createTruncatedTextElement(PrivateKeys.bank_dh, 35);
  setTimeout(() => outputElement.appendChild(sharedKey), 5500);


  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // User generated Schnorr public key

  const schnorrLine = document.createElement('p');
  schnorrLine.style.margin = "3px";
  schnorrLine.style.color = "green";
  schnorrLine.style.textDecoration = "underline";

  setTimeout(() => outputElement.appendChild(schnorrLine), 6500);
  setTimeout(() => schnorrLine.textContent = "User generated private Schnorr key:", 6500);
  setTimeout(() => outputElement.appendChild(user_schnorr), 6500);

  // Display the hash digest and the public Schnorr key, generated from the shared key
  const hashDigestLine = document.createElement('p');
  hashDigestLine.style.margin = "3px";
  hashDigestLine.style.color = "green";
  hashDigestLine.style.textDecoration = "underline";
  const publicKeyAsHexLine = document.createElement('p');
  publicKeyAsHexLine.style.margin = "3px";
  publicKeyAsHexLine.style.color = "green";
  publicKeyAsHexLine.style.textDecoration = "underline";

  const hashDigest = await getPublicKeyData("Schnorr_get_message_digest")
  const hashDigestShortened = createTruncatedTextElement(hashDigest.message_hash_digest, 35);
  const publicSchnorrKey = await getPublicKeyData("Public_Key_Schnorr")
  const publicSchnorrKeyShortened = createTruncatedTextElement(publicSchnorrKey.public_key_sh, 35);

  // Display the hash digest of the shared key
  setTimeout(() => outputElement.appendChild(hashDigestLine), 7500);
  setTimeout(() => hashDigestLine.textContent = "Hash digest:", 7500);
  setTimeout(() => outputElement.appendChild(hashDigestShortened), 7500);

  // Display the private Schnorr key as a hexadecimal string
  setTimeout(() => outputElement.appendChild(publicKeyAsHexLine), 8500);
  setTimeout(() => publicKeyAsHexLine.textContent = "Generated public Schnorr Key using privete Schnorr:", 8500);
  setTimeout(() => outputElement.appendChild(publicSchnorrKeyShortened), 8500);

  // Display the signature generated from the hash digest and the private Schnorr key
  const SignatureLine = document.createElement('p');
  SignatureLine.style.margin = "3px";
  SignatureLine.style.color = "green";
  SignatureLine.style.textDecoration = "underline";

  const Signature = await getPublicKeyData("Schnorr_sign_via_private_key")
  const SignatureShortened = createTruncatedTextElement(Signature.Signature, 35);

  setTimeout(() => outputElement.appendChild(SignatureLine), 9500);
  setTimeout(() => SignatureLine.textContent = "Generated Schnorr signature:", 9500);
  setTimeout(() => outputElement.appendChild(SignatureShortened), 9500);


  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // User encrypts the message using the shared key
  const encryptingMessage = createTruncatedTextElement("Encrypted message using the shared key...", 50);
  encryptingMessage.style.margin = "3px";
  encryptingMessage.style.color = "green";
  encryptingMessage.style.textDecoration = "underline";

  const encryptedMessage = await getPublicKeyData("EncryptedSentence");
  const encryptedMessageShortened = createTruncatedTextElement(encryptedMessage.EncryptedSentence.slice(3, encryptedMessage.EncryptedSentence.length - 2), 50);

  setTimeout(() => outputElement.appendChild(encryptingMessage), 10500);
  setTimeout(() => outputElement.appendChild(encryptedMessageShortened), 10500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // Display the bank button

  setTimeout(() => {
    document.getElementById('bankButton').style.backgroundColor = "green";
    document.getElementById('bankButton').textContent = "Sign and send to Bank";
  }, 11500);

});

// Send the encrypted message and the signature to the bank, with the public key
document.getElementById('bankButton').addEventListener('click', async function () {

  // Animation code:
  const dotContainer = document.querySelector('.passing-dots2');
  const dotCount = 6;
  const dotDuration = 1000; // Each dot appears for 0.5 seconds
  const delayBetweenDots = 150;
  for (let i = dotCount; i > 0; i--) {
    setTimeout(() => {
      const dot = document.createElement('div');
      dot.classList.add('dot');
      dotContainer.appendChild(dot);

      setTimeout(() => dot.remove(), dotDuration);
    }, i * delayBetweenDots);
  }

  setTimeout(() => {
    for (let i = dotCount; i > 0; i--) {
      setTimeout(() => {
        const dot = document.createElement('div');
        dot.classList.add('dot');
        dotContainer.appendChild(dot);

        setTimeout(() => dot.remove(), dotDuration);
      }, i * delayBetweenDots);
    }
  }, 2000);

  const bankMessageLine = document.createElement('p');
  bankMessageLine.style.margin = "5px";
  bankMessageLine.style.color = "green";
  bankMessageLine.style.textDecoration = "underline";

  const encryptedMessage = await getPublicKeyData("EncryptedSentence")
  const encryptedMessageShortened = createTruncatedTextElement(encryptedMessage.EncryptedSentence.slice(3, encryptedMessage.EncryptedSentence.length - 2), 50);


  setTimeout(() => bankElement.appendChild(bankMessageLine), 500);
  setTimeout(() => bankMessageLine.textContent = "Message received:", 500);
  setTimeout(() => bankElement.appendChild(encryptedMessageShortened), 500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // Display the signature received from the user

  const signatureReceivedLine = document.createElement('p');
  signatureReceivedLine.style.margin = "5px";
  signatureReceivedLine.style.color = "green";
  signatureReceivedLine.style.textDecoration = "underline";

  const signatureReceived = await getPublicKeyData("Schnorr_sign_via_private_key")
  const signatureReceivedShortened = createTruncatedTextElement(signatureReceived.Signature, 35);

  setTimeout(() => bankElement.appendChild(signatureReceivedLine), 1500);
  setTimeout(() => signatureReceivedLine.textContent = "Signature received:", 1500);
  setTimeout(() => bankElement.appendChild(signatureReceivedShortened), 1500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // Display the hash digest received from the user
  const publicSchnorrReceived = document.createElement('p');
  publicSchnorrReceived.style.margin = "5px";
  publicSchnorrReceived.style.color = "green";
  publicSchnorrReceived.style.textDecoration = "underline";

  const publicKey = await getPublicKeyData("Public_Key_schnorr")
  const publicKeyShortened = createTruncatedTextElement(publicKey.public_key_sh, 35);

  setTimeout(() => bankElement.appendChild(publicSchnorrReceived), 2500);
  setTimeout(() => publicSchnorrReceived.textContent = "Public Schnorr key received:", 2500);
  setTimeout(() => bankElement.appendChild(publicKeyShortened), 2500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  // Decode the encrypted message using the public key and verify the signature
  const decodedMessageLine = document.createElement('p');
  decodedMessageLine.style.margin = "5px";
  decodedMessageLine.style.color = "green";
  decodedMessageLine.style.textDecoration = "underline";

  const decodedMessage = await getPublicKeyData("SentenceToSend")
  const decodedMessageShortened = createTruncatedTextElement(decodedMessage.Sentence, 50);

  const checkingSignature = createTruncatedTextElement("Checking signature...", 50);
  const signatureVerified = createTruncatedTextElement("Signature verified!!!!", 50);
  const preparingPublicKey = createTruncatedTextElement("Preparing shared key...", 50);
  const decryptingMessage = createTruncatedTextElement("Decrypting message with RC6...", 50);
  const success = createTruncatedTextElement("Success!", 50);
  success.style.color = "green";

  setTimeout(() => bankElement.appendChild(checkingSignature), 3500);
  setTimeout(() => bankElement.appendChild(signatureVerified), 4500);
  setTimeout(() => bankElement.appendChild(preparingPublicKey), 5500);
  setTimeout(() => bankElement.appendChild(decryptingMessage), 6500);
  setTimeout(() => bankElement.appendChild(success), 7500);


  setTimeout(() => bankElement.appendChild(decodedMessageLine), 8500);
  setTimeout(() => decodedMessageLine.textContent = "Decoded message:", 8500);
  setTimeout(() => bankElement.appendChild(decodedMessageShortened), 8500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  setTimeout(() => {
    document.getElementById('successButton').style.backgroundColor = "blue";
    document.getElementById('successButton').textContent = "Send \"Successful Payment\" to User";
  }, 9500);

  // Send an encoded "Success" message to the user
  const successMessageLine = document.createElement('p');
  successMessageLine.style.margin = "5px";
  successMessageLine.style.color = "red";

  document.getElementById('bankButton').classList.add('sendToUser');
});


document.getElementById('successButton').addEventListener('click', async function () {
  // Clear output block
  while (document.getElementById('output').firstChild) {
    document.getElementById('output').removeChild(document.getElementById('output').firstChild);
  }

  document.getElementById('bankButton').style.backgroundColor = "transparent";
  document.getElementById('bankButton').textContent = "";

  // Animation code:
  const dotContainer = document.querySelector('.passing-dots2');
  const dotCount = 6;
  const dotDuration = 1000; // Each dot appears for 0.5 seconds
  const delayBetweenDots = 150;
  for (let i = dotCount; i > 0; i--) {
    setTimeout(() => {
      const dot = document.createElement('div');
      dot.classList.add('dot');
      dotContainer.appendChild(dot);

      setTimeout(() => dot.remove(), dotDuration);
    }, i * delayBetweenDots);
  }

  setTimeout(() => {
    for (let i = dotCount; i > 0; i--) {
      setTimeout(() => {
        const dot = document.createElement('div');
        dot.classList.add('dot');
        dotContainer.appendChild(dot);

        setTimeout(() => dot.remove(), dotDuration);
      }, i * delayBetweenDots);
    }
  }, 2000);

  const encryptionSuccessMessageLine = document.createElement('p');
  encryptionSuccessMessageLine.style.margin = "5px";
  encryptionSuccessMessageLine.style.color = "green";

  setTimeout(() => document.getElementById('output').appendChild(encryptionSuccessMessageLine), 500);
  setTimeout(() => encryptionSuccessMessageLine.textContent = "Encrypting \"Success\" message to user", 500);

  /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

  const messageToUser = await getPublicKeyData("EncryptedSentenceAck")

  // Encrypt the "Success" message using the public key, and send it to the user
  const encryptingMessage = createTruncatedTextElement("Encrypted message:", 50);
  const encryptedSuccess = createTruncatedTextElement(messageToUser.EncryptedSentence.slice(3, messageToUser.EncryptedSentence.length - 2), 50);
  encryptingMessage.style.color = "green";

  setTimeout(() => document.getElementById('output').appendChild(encryptingMessage), 1500);
  setTimeout(() => document.getElementById('output').appendChild(encryptedSuccess), 1500);

  // Send the encoded "Success" message to the user
  const successMessageLine = document.createElement('p');
  successMessageLine.style.margin = "5px";
  successMessageLine.style.color = "green";
  successMessageLine.style.textDecoration = "underline";

  setTimeout(() => document.getElementById('output').appendChild(successMessageLine), 2500);

  setTimeout(() => {
    document.getElementById("sendToUser").style.backgroundColor = "green";
    document.getElementById("sendToUser").textContent = "Send to User";
  }, 3500);

});

document.getElementById("sendToUser").addEventListener('click', async function () {
  // Animation code:
  const dotContainer = document.querySelector('.passing-dots1');
  const dotCount = 6;
  const dotDuration = 1000; // Each dot appears for 0.5 seconds
  const delayBetweenDots = 150;
  for (let i = dotCount; i > 0; i--) {
    setTimeout(() => {
      const dot = document.createElement('div');
      dot.classList.add('dot');
      dotContainer.appendChild(dot);

      setTimeout(() => dot.remove(), dotDuration);
    }, i * delayBetweenDots);
  }

  const userMessageLine = document.createElement('p');
  userMessageLine.style.margin = "5px";
  userMessageLine.style.color = "green";

  setTimeout(() => document.getElementById('user').appendChild(userMessageLine), 500);
  setTimeout(() => userMessageLine.textContent = "Successfully paid!", 1500);

});

async function getPublicKeyData(fileName) {
  fileName = './JSONFiles/' + fileName + ".json";
  try {
    const response = await fetch(fileName);
    const data = await response.json();
    // Use publicKeyData here
    return data;
  } catch (error) {
    console.error("Error fetching public key file:", error);
  }
}

function createTruncatedTextElement(text, maxLength) {
  const span = document.createElement('p');
  span.style.margin = "5px";
  shortenedText = createShortText(text, maxLength);

  if (text.length > maxLength) {
    span.textContent = shortenedText; // Set the shortened text as content
    span.title = text; // Set the full text as hover text
    span.classList.add('truncated'); // Add a class for styling
  }
  else {
    span.textContent = text;
  }
  return span;
}

function createShortText(text, maxLength) {
  if (text.length > maxLength) {
    return text.slice(0, maxLength) + '...';
  }
  return text;
}

function addStyleToHeadForTruncatedText() {
  const style = document.createElement('style');
  style.textContent = `
  .truncated {
    display: inline-block;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    cursor: help; /* Change cursor on hover */
    height: 15px;
    margin: 0px;
    padding: 0px;
    text-decoration: underline; /* Reset default underline */
  }

  .truncated:hover {
    text-decoration: underline; /* Apply underline on hover */
  }
`;
  document.head.appendChild(style);
}